[package]
name = "dustlib_k"
version = "0.2.0"
authors = ["Dust Contributors <contributors@dustlang.org>"]
edition = "2026"
description = "Kâ€‘regime standard library for the Dust Programming Language"
license = "DOSL"

[workspace]
members = [
    "sector/dustlib-k"
]

# The `sector/dustlib-k` member contains all `.ds` source files for the
# library.  Additional sectors may be added in future.
